# Generated by Django 2.0.2 on 2018-03-17 07:16

from django.db import migrations


def gen_default(apps, schema_editor):
    """Generate default models for the accounts application"""
    Peer = apps.get_model("accounts", "Peer")
    peer = Peer()
    peer.name = "Unknown Peer"
    peer.save()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(gen_default),
    ]
