# Generated by Django 2.0.2 on 2018-03-17 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_generate_default_objects'),
    ]

    operations = [
        migrations.AddField(
            model_name='peer',
            name='class_type',
            field=models.CharField(default='Bier', editable=False, max_length=50),
            preserve_default=False,
        ),
    ]
