# Generated by Django 2.0.1 on 2018-01-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_symbols'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='symbols',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
