# Generated by Django 2.0.5 on 2018-05-06 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0001_initial'),
        ('accounts', '0004_auto_20180408_1110'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Address',
            new_name='CryptoAddress',
        ),
    ]
