# Generated by Django 2.0.5 on 2018-05-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180506_1126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cryptoaddress',
            options={'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='cryptoaddress',
            name='watch',
            field=models.BooleanField(default=False),
        ),
    ]
