# Generated by Django 2.0.2 on 2018-03-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cc_id', models.IntegerField(unique=True)),
                ('img_url', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('symbol', models.CharField(max_length=10)),
                ('coin_name', models.CharField(max_length=200)),
                ('full_name', models.CharField(max_length=200)),
            ],
        ),
    ]
