# Generated by Django 2.0.5 on 2018-05-10 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coin',
            options={'ordering': ('symbol',)},
        ),
    ]
