# Generated by Django 2.0.3 on 2018-04-01 17:15

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('accounts', '0003_peer_class_type'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ('-date',)},
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='source_account',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='target_account',
        ),
        migrations.AddField(
            model_name='transaction',
            name='source_peer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='source_peer', to='accounts.Peer'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='target_peer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='target_peer', to='accounts.Peer'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='book_price_fee_btc',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='book_price_fee_eur',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fee_amount',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fee_currency',
            field=models.CharField(default='---', max_length=10),
        ),
    ]
