# Generated by Django 2.0.2 on 2018-02-25 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='aquired_amount',
            new_name='acquired_amount',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='aquired_currency',
            new_name='acquired_currency',
        ),
    ]
