# Generated by Django 2.0.2 on 2018-03-26 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('transactions', '0002_auto_20180325_1753'), ('transactions', '0003_auto_20180326_1633')]

    dependencies = [
        ('transactions', '0001_initial'),
        ('accounts', '0003_peer_class_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='source_account',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='target_account',
        ),
        migrations.AddField(
            model_name='transaction',
            name='source_peer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='source_peer', to='accounts.Peer'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='target_peer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='target_peer', to='accounts.Peer'),
        ),
    ]
