# Generated by Django 2.0.3 on 2018-04-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20180325_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='icon',
            field=models.CharField(default='help_outline', max_length=100),
        ),
    ]
