# Generated by Django 2.0.3 on 2018-04-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='acquired_amount',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='acquired_currency',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='spent_amount',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='spent_currency',
            field=models.CharField(default='', max_length=10),
        ),
    ]
