# Generated by Django 2.0.3 on 2018-04-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20180408_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='acquired_currency',
            field=models.CharField(default='---', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='spent_currency',
            field=models.CharField(default='---', max_length=10),
        ),
    ]
